import { createContext } from "react";
export default createContext({
  handleLogout: () => {},
  handleLoginAsGuest: () => {},
  userData: [],
  selectedMovie: {},
  handleSelectMovie: () => {},
  handleResetSelectedMovie: () => {},
  allMovies: [],
  isLoading: false,
  handleGetAllMovies: () => {},
  handleGetUserData: () => {},
  handleAddMovieToList: () => {},
  userMovieList: [],
  bannerMovie: {},
  handleSetBannerMovie: () => {},
  filters: [],
  handleAddNewComment: () => {},
  handleEditComment: () => {},
  handleDeleteComment: () => {},
  handleChangeProfileImage: () => {},
  handleChangeSearchQuery: () => {},
  searchQuery: "",
  handleToggleSearchBar: () => {},
  handleClearSearchQuery: () => {},
  handleToggleOffSearchBar: () => {},
  setSearchBarState: () => {},
  isAddToListLoading: false,
});
