export const filtersList = [
  "Action & Adventure",
  "Anime",
  "Award-Winning",
  "Children & Family Movies",
  "Classic",
  "Comedies",
  "Crime Movies",
  "Documentaries",
  "Dramas",
  "Fantasy Movie",
  "Horror",
  "Independent",
  "Music & Musicals",
  "Romantic",
  "Sci-Fi Movies",
  "Sports",
  "Thriller",
];
